services:
  freeipa-server:
    container_name: freeipa-server
    hostname: ipa.example.test
    image: freeipa/freeipa-server:fedora-36
    privileged: true
    volumes:
      - type: volume
        source: freeipa-data
        target: /data
      - type: volume
        source: freeipa-run
        target: /run
      - type: tmpfs
        target: /tmp
    ports:
      - 127.0.0.1:443:443
      - 127.0.0.1:80:80
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=0
    environment:
      - DEBUG_TRACE=1
    command: [
      "--realm", "EXAMPLE.TEST",
      "--domain", "example.test",
      "--ds-password", "password",
      "--admin-password", "password",
      "--hostname", "ipa.example.test",
      "--no-ntp",
      "-U"
    ]

volumes:
  freeipa-data:
    name: freeipa-data
  freeipa-run:
    name: freeipa-run